### ISSUE TITLE
release

### ISSUE THREAD

**Issue by SayaAEP** [Xtr126/CursorChangerGearlock#2]
I can't wait for the latest release since it's been merged https://github.com/Xtr126/CursorChangerGearlock/pull/1

I made this issue because:I don't know how to make a gearlock extension

**Comment by Xtr126** [comment]
Hi, I will try to release it this week soon after some more little improvements. You can just pack all the files in this repo as a 7-zip archive and rename to .gxp to make gearlock extension. Or using gearlock-dev-kit.

**Comment by Xtr126** [comment]
v1.1 is released
